### ISSUE TITLE
[Feature request] Variable playback speed of voice message

### ISSUE THREAD

**Issue by Duvio** [SchildiChat/SchildiChat-android#209] opened 2023-09-19 08:05 UTC
**Is your feature request related to a problem? Please describe.**
People sending long voice messages.

**Describe the solution you'd like**
Add ability to listen to voice messages on higher playback speeds.

**Additional context**
WhatsApp for example already supports this. There is a button right next to the voice message where you can set the playback speed to 1x, 1.5x and 2x.

**Comment by SpiritCroc** [comment] 2023-09-19 08:11
Duplicate of https://github.com/SchildiChat/SchildiChat-android/issues/109.

**Closed as not planned by SpiritCroc** 2023-09-19 08:11 UTC
Labels: duplicate
