### ISSUE TITLE
Multi account

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [SchildiChat/SchildiChat-android#34] opened 2020-12-28 10:36 UTC
With xmpp messenger, several profiles can be entered and then switched over.

With matrix messengers, this is only possible for one account.

This is stupid if your main matrix account is not available, but you urgently need to read that message.

**Comment by SpiritCroc** [comment] 2020-12-28 10:38
Duplicate of https://github.com/SchildiChat/SchildiChat-android/issues/21.

**Closed as completed by SpiritCroc** 2020-12-28 10:38 UTC
Labels: duplicate
